import styles from "./styles/page.module.css"
import "./styles/global.css"; // ✅ Se importa sin asignarlo a una variable


export const metadata = {
  title: "Jacqueline Urban Portfolio",
  description: "Generated by me",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
