import styles from "./page.module.css";
import "./globals.css";

export const metadata = {
  title: "Jacqueline Urban Portfolio",
  description: "Generated by me",
};

export default function RootLayout({ children }) {
  return (
    <html className="globalHtml">
      <body className="globalBody">
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
